// engine.js — generic Markdown → PPTX engine for the yyy paper-slide house style.
// YOU DO NOT EDIT THIS FILE. Put content in content.md, deck-specific slides in custom.js.
//
// Public API:
//   const { buildDeck } = require("./engine");
//   buildDeck({ md, custom, out });   // md = content.md string, custom = map of renderers
//
// Supported markdown (Style 1):
//   ---  frontmatter: title / author / date / citation / affiliations / citations / link  ---
//   # text                  -> section divider (left-middle, **bold** = accent)
//   ## title                -> content slide title; body below decides the type
//     plain line            -> lead text under the title
//     - bullet              -> bullets slide
//     ::: boxes ... :::      -> row of boxes (one "- label" per box)
//     ::: pillars ... :::    -> big-number cards ("- label | big | gloss")
//     ::: cards ... :::       -> accent-bar cards ("- label | gloss")
//     ::: quote ... :::       -> big quote card (first line big, rest sub)
//     ::: outline ... :::     -> numbered outline ("- head | sub" or "- n | head | sub")
//     caption: text          -> grey caption at the bottom of the current slide
//     highlight: text        -> tinted emphasis card (**bold** = accent)
//   > text                   -> one-line takeaway slide (**bold** = accent)
//   @slide name              -> insert a deck-specific slide from custom.js

const pptxgen = require("pptxgenjs");

// ---- House style (the ONE config block; change here to retheme) ----
const BG = "FAF8F4";   // warm off-white
const TEXT = "2B2B2B"; // charcoal
const SEC = "6B6B66";  // warm grey
const ACC = "C2643C";  // terracotta accent
const TINT = "F0E4DC"; // light terracotta backing
const FONT = "Helvetica";
const PAGE_W = 13.333, PAGE_H = 7.5, ML = 0.7, USABLE = PAGE_W - 2 * ML;

// ============================================================
// Parser: markdown string -> { meta, slides[] }
// ============================================================
function parse(md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let i = 0;
  const meta = {};

  // frontmatter
  if (lines[0] && lines[0].trim() === "---") {
    i = 1;
    let key = null;
    for (; i < lines.length; i++) {
      const ln = lines[i];
      if (ln.trim() === "---") { i++; break; }
      const m = ln.match(/^(\w+):\s*(.*)$/);
      if (m && !ln.startsWith("  ")) {
        key = m[1];
        meta[key] = m[2] === "|" ? "" : m[2];
        if (m[2] === "|") meta[key + "__multi"] = true;
      } else if (key && meta[key + "__multi"]) {
        meta[key] += (meta[key] ? "\n" : "") + ln.replace(/^\s{0,2}/, "");
      }
    }
  }

  const slides = [];
  let cur = null;
  const finish = () => { if (cur) { slides.push(finalize(cur)); cur = null; } };

  for (; i < lines.length; i++) {
    let ln = lines[i];
    const t = ln.trim();
    if (t === "") continue;

    if (t.startsWith("# ")) { finish(); slides.push({ type: "divider", text: t.slice(2).trim() }); continue; }
    if (t.startsWith("> ")) { finish(); slides.push({ type: "takeaway", text: t.slice(2).trim() }); continue; }
    if (t.startsWith("@slide ")) { finish(); slides.push({ type: "custom", name: t.slice(7).trim() }); continue; }
    if (t.startsWith("## ")) { finish(); cur = { title: t.slice(3).trim(), lead: null, bullets: [], block: null, caption: null, highlight: null }; continue; }

    if (t.startsWith(":::")) {
      const btype = t.slice(3).trim();
      const inner = [];
      for (i++; i < lines.length; i++) { if (lines[i].trim() === ":::") break; inner.push(lines[i]); }
      if (!cur) cur = { title: null, lead: null, bullets: [], block: null, caption: null, highlight: null };
      cur.block = { type: btype, inner };
      continue;
    }
    if (!cur) continue;
    if (t.startsWith("caption:")) { cur.caption = t.slice(8).trim(); continue; }
    if (t.startsWith("highlight:")) { cur.highlight = t.slice(10).trim(); continue; }
    if (t.startsWith("- ")) { cur.bullets.push(t.slice(2).trim()); continue; }
    if (!cur.block && cur.bullets.length === 0) { cur.lead = cur.lead ? cur.lead + "\n" + t : t; continue; }
  }
  finish();
  return { meta, slides };
}

function finalize(cur) {
  const base = { title: cur.title, lead: cur.lead, caption: cur.caption, highlight: cur.highlight };
  if (cur.block) {
    const { type, inner } = cur.block;
    const items = inner.map(l => l.trim()).filter(Boolean).map(l => l.replace(/^- /, ""));
    if (type === "quote") {
      const raw = inner.map(l => l.trim()).filter(Boolean);
      return { ...base, type: "quote", big: raw[0] || "", subs: raw.slice(1) };
    }
    if (type === "boxes") return { ...base, type: "boxes", boxes: items };
    if (type === "pillars") return { ...base, type: "pillars", cards: items.map(splitPipe3) };
    if (type === "cards") return { ...base, type: "cards", cards: items.map(splitPipe2) };
    if (type === "outline") return { ...base, type: "outline", rows: items.map(splitOutline) };
    return { ...base, type, items };
  }
  return { ...base, type: "bullets", bullets: cur.bullets };
}
const splitPipe3 = s => { const p = s.split("|").map(x => x.trim()); return { label: p[0], big: p[1] || "", gloss: p[2] || "" }; };
const splitPipe2 = s => { const p = s.split("|").map(x => x.trim()); return { label: p[0], gloss: p[1] || "" }; };
const splitOutline = (s, idx) => { const p = s.split("|").map(x => x.trim()); return p.length >= 3 ? { num: p[0], head: p[1], sub: p[2] } : { num: String(idx + 1), head: p[0], sub: p[1] || "" }; };

// ============================================================
// Build
// ============================================================
function buildDeck({ md, custom = {}, out = "deck.pptx" }) {
  const { meta, slides } = parse(md);
  deepNL(slides); // turn literal "\n" in markdown fields into real line breaks
  const pres = new pptxgen();
  pres.layout = "LAYOUT_WIDE";
  if (meta.title) pres.title = meta.title;
  if (meta.author) pres.author = meta.author;

  const shadow = () => ({ type: "outer", color: "000000", blur: 7, offset: 3, angle: 135, opacity: 0.1 });
  const card = (s, x, y, w, h, fill = "FFFFFF") => s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, rectRadius: 0.08, fill: { color: fill }, line: { color: "EBE9E5", width: 1 }, shadow: shadow() });
  const bar = (s, x, y, h, w = 0.1, color = ACC) => s.addShape(pres.shapes.RECTANGLE, { x, y, w, h, fill: { color } });
  const title = (s, t) => s.addText(t, { x: ML, y: 0.45, w: USABLE, h: 0.9, fontFace: FONT, fontSize: 34, bold: true, color: TEXT, align: "left", valign: "top", margin: 0 });
  const rich = (str, color = TEXT) => {
    const parts = []; const re = /\*\*(.+?)\*\*/g; let last = 0, m;
    while ((m = re.exec(str))) { if (m.index > last) parts.push({ text: str.slice(last, m.index), options: { color } }); parts.push({ text: m[1], options: { color: ACC, bold: true } }); last = re.lastIndex; }
    if (last < str.length) parts.push({ text: str.slice(last), options: { color } });
    return parts.length ? parts : [{ text: str, options: { color } }];
  };
  const caption = (s, text) => { if (text) s.addText(text, { x: ML, y: 5.95, w: USABLE, h: 0.5, fontFace: FONT, fontSize: 18, color: SEC, align: "left", margin: 0 }); };
  const api = { pres, BG, TEXT, SEC, ACC, TINT, FONT, PAGE_W, PAGE_H, ML, USABLE, card, bar, title, rich, shadow, caption };

  // ---- front matter ----
  renderCover(pres, meta, { bar });
  if (meta.citation) renderReference(pres, meta, { card, bar, title });

  // ---- renderers for md slide types ----
  const R = {
    divider(s, sl) {
      s.addText(rich(sl.text), { x: ML, y: 0, w: 11, h: PAGE_H, fontFace: FONT, fontSize: 48, bold: true, align: "left", valign: "middle", lineSpacingMultiple: 1.05, margin: 0 });
    },
    takeaway(s, sl) {
      s.addText(rich(sl.text), { x: ML, y: 0, w: USABLE, h: PAGE_H, fontFace: FONT, fontSize: 44, bold: true, align: "left", valign: "middle", margin: 0 });
    },
    bullets(s, sl) {
      title(s, sl.title);
      let y = 1.7;
      if (sl.lead) { s.addText(sl.lead, { x: ML, y: 1.5, w: USABLE, h: 0.6, fontFace: FONT, fontSize: 24, color: TEXT, align: "left", margin: 0 }); y = 2.3; }
      if (sl.bullets.length) s.addText(sl.bullets.map((b, i) => ({ text: b, options: { bullet: true, breakLine: i < sl.bullets.length - 1 } })), { x: ML, y, w: USABLE, h: 3.0, fontFace: FONT, fontSize: 28, color: TEXT, paraSpaceAfter: 14, margin: 0 });
      if (sl.highlight) { card(s, ML, 4.6, USABLE, 1.5, TINT); s.addText(rich(sl.highlight), { x: ML + 0.45, y: 4.6, w: USABLE - 0.9, h: 1.5, fontFace: FONT, fontSize: 30, bold: true, align: "left", valign: "middle", margin: 0 }); }
      caption(s, sl.caption);
    },
    boxes(s, sl) {
      title(s, sl.title);
      const leadLines = sl.lead ? sl.lead.split("\n").length : 0;
      if (sl.lead) s.addText(sl.lead, { x: ML, y: 1.6, w: USABLE, h: 0.3 + leadLines * 0.4, fontFace: FONT, fontSize: 24, color: TEXT, align: "left", valign: "top", lineSpacingMultiple: 1.05, margin: 0 });
      const n = sl.boxes.length, gap = 0.2, bw = Math.min(2.6, (USABLE - (n - 1) * gap) / n), total = n * bw + (n - 1) * gap;
      let bx = (PAGE_W - total) / 2; const by = sl.lead ? 3.0 + leadLines * 0.35 : 3.0;
      sl.boxes.forEach(b => { s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: bx, y: by, w: bw, h: 1.7, rectRadius: 0.08, fill: { color: "FFFFFF" }, line: { color: TINT, width: 1.5 }, shadow: shadow() }); s.addText(b, { x: bx + 0.2, y: by, w: bw - 0.35, h: 1.7, fontFace: FONT, fontSize: 19, bold: true, color: TEXT, align: "left", valign: "middle", margin: 0 }); bx += bw + gap; });
      caption(s, sl.caption);
    },
    pillars(s, sl) {
      title(s, sl.title);
      if (sl.lead) s.addText(sl.lead, { x: ML, y: 1.5, w: USABLE, h: 0.5, fontFace: FONT, fontSize: 22, color: SEC, align: "left", margin: 0 });
      const n = sl.cards.length, gap = 0.4, cw = (USABLE - (n - 1) * gap) / n, cy = sl.lead ? 2.3 : 2.1, ch = 3.2;
      sl.cards.forEach((c, i) => { const cx = ML + i * (cw + gap); card(s, cx, cy, cw, ch); bar(s, cx, cy, ch); s.addText(c.label, { x: cx + 0.35, y: cy + 0.3, w: cw - 0.5, h: 0.5, fontFace: FONT, fontSize: 18, bold: true, color: SEC, align: "left", margin: 0 }); s.addText(c.big, { x: cx + 0.35, y: cy + 0.9, w: cw - 0.5, h: 1.0, fontFace: FONT, fontSize: 44, bold: true, color: ACC, align: "left", valign: "middle", margin: 0 }); s.addText(c.gloss, { x: cx + 0.35, y: cy + 2.0, w: cw - 0.6, h: 1.0, fontFace: FONT, fontSize: 16, color: TEXT, align: "left", valign: "top", lineSpacingMultiple: 1.1, margin: 0 }); });
      caption(s, sl.caption);
    },
    cards(s, sl) {
      title(s, sl.title);
      if (sl.lead) s.addText(sl.lead, { x: ML, y: 1.55, w: USABLE, h: 0.6, fontFace: FONT, fontSize: 24, color: TEXT, align: "left", margin: 0 });
      const n = sl.cards.length, gap = 0.4, cw = (USABLE - (n - 1) * gap) / n, cy = sl.lead ? 2.6 : 2.2, ch = 2.5;
      sl.cards.forEach((c, i) => { const cx = ML + i * (cw + gap); card(s, cx, cy, cw, ch); bar(s, cx, cy, ch); s.addText(c.label, { x: cx + 0.3, y: cy + 0.3, w: cw - 0.45, h: 0.6, fontFace: FONT, fontSize: 22, bold: true, color: ACC, align: "left", margin: 0 }); s.addText(c.gloss, { x: cx + 0.3, y: cy + 1.0, w: cw - 0.5, h: 1.3, fontFace: FONT, fontSize: 16, color: TEXT, align: "left", valign: "top", lineSpacingMultiple: 1.1, margin: 0 }); });
      caption(s, sl.caption);
    },
    quote(s, sl) {
      if (sl.title) title(s, sl.title);
      const cy = sl.title ? 2.0 : 2.3;
      card(s, ML, cy, USABLE, 2.4);
      s.addText(sl.big, { x: ML + 0.5, y: cy + 0.45, w: USABLE - 1, h: 1.0, fontFace: FONT, fontSize: 40, bold: true, color: ACC, align: "left", valign: "middle", margin: 0 });
      if (sl.subs.length) s.addText(sl.subs.map((b, i) => ({ text: b, options: { breakLine: i < sl.subs.length - 1 } })), { x: ML + 0.5, y: cy + 1.4, w: USABLE - 1, h: 0.9, fontFace: FONT, fontSize: 22, color: TEXT, align: "left", valign: "middle", paraSpaceAfter: 4, margin: 0 });
      caption(s, sl.caption);
    },
    outline(s, sl) {
      title(s, sl.title || "Outline");
      const rh = 0.8; let oy = 1.75;
      sl.rows.forEach(r => { s.addText([{ text: r.num + "   ", options: { color: ACC, bold: true } }, { text: r.head, options: { color: TEXT, bold: true } }, { text: r.sub ? "    " + r.sub : "", options: { color: SEC, fontSize: 18 } }], { x: ML, y: oy, w: USABLE, h: rh, fontFace: FONT, fontSize: 26, align: "left", valign: "middle", margin: 0 }); oy += rh; });
    },
  };

  let page = 0;
  for (const sl of slides) {
    const s = pres.addSlide();
    s.background = { color: BG };
    if (sl.type === "custom") {
      const fn = custom[sl.name];
      if (fn) fn(s, sl, api);
      else { s.addShape(pres.shapes.RECTANGLE, { x: ML, y: 2.5, w: USABLE, h: 2.0, fill: { color: TINT }, line: { color: ACC, width: 1.25, dashType: "dash" } }); s.addText("@slide " + sl.name + "  (not found in custom.js)", { x: ML, y: 3.2, w: USABLE, h: 0.6, fontFace: FONT, fontSize: 16, italic: true, color: SEC, align: "center", margin: 0 }); }
    } else if (R[sl.type]) {
      R[sl.type](s, sl);
    }
    const noNum = sl.type === "outline" || (sl.type === "custom" && custom[sl.name] && custom[sl.name].nonum);
    if (!noNum) { page++; s.addText(String(page), { x: PAGE_W - 1.1, y: PAGE_H - 0.45, w: 0.6, h: 0.3, fontFace: FONT, fontSize: 11, color: SEC, align: "right", margin: 0 }); }
  }
  return pres.writeFile({ fileName: out });

  // --- front-matter renderers (defined as hoisted fns) ---
  function renderCover(pres, meta, h) {
    const s = pres.addSlide(); s.background = { color: BG };
    h.bar(s, 0, 0, PAGE_H, 0.22);
    s.addText(meta.title || "Untitled", { x: 1.0, y: 2.5, w: 11.3, h: 2.2, fontFace: FONT, fontSize: 48, bold: true, color: TEXT, align: "left", valign: "top", lineSpacingMultiple: 1.05, margin: 0 });
    s.addText([{ text: meta.author || "", options: { color: TEXT, bold: true } }, { text: meta.date ? "      " + meta.date : "", options: { color: SEC } }], { x: 1.0, y: 5.0, w: 11, h: 0.5, fontFace: FONT, fontSize: 20, align: "left", margin: 0 });
  }
  function renderReference(pres, meta, h) {
    const s = pres.addSlide(); s.background = { color: BG };
    h.title(s, "Reference");
    h.card(s, ML, 1.7, USABLE, 1.85); h.bar(s, ML, 1.7, 1.85, 0.12);
    s.addText(meta.citation.split("\n").map((l, i, a) => ({ text: l, options: { breakLine: i < a.length - 1, bold: i === 1, italic: i >= 2, color: i >= 2 ? SEC : TEXT } })), { x: ML + 0.45, y: 1.7, w: USABLE - 0.9, h: 1.85, fontFace: FONT, fontSize: 19, align: "left", valign: "middle", lineSpacingMultiple: 1.15, margin: 0 });
    let y = 3.9;
    if (meta.affiliations) { meta.affiliations.split("\n").forEach(l => { s.addText(l, { x: ML, y, w: USABLE, h: 0.5, fontFace: FONT, fontSize: 18, color: TEXT, align: "left", margin: 0 }); y += 0.5; }); }
    if (meta.citations) { s.addText([{ text: "Citations:  ", options: { bold: true, color: SEC } }, { text: meta.citations, options: { color: ACC, bold: true } }], { x: ML, y: y + 0.1, w: USABLE, h: 0.5, fontFace: FONT, fontSize: 20, align: "left", margin: 0 }); y += 0.6; }
    if (meta.link) s.addText([{ text: "Link:  ", options: { bold: true, color: SEC } }, { text: meta.link, options: { color: ACC } }], { x: ML, y: y + 0.1, w: USABLE, h: 0.5, fontFace: FONT, fontSize: 20, align: "left", margin: 0 });
  }
}

function deepNL(o) {
  if (Array.isArray(o)) { o.forEach(deepNL); return o; }
  if (o && typeof o === "object") { for (const k in o) o[k] = typeof o[k] === "string" ? o[k].replace(/\\n/g, "\n") : (deepNL(o[k]), o[k]); return o; }
  return o;
}

module.exports = { buildDeck, parse };
